---
title: "Regressions"
output: html_notebook
---

```{r}
shhh <- suppressPackageStartupMessages # It's a library, so shhh!

shhh(library( mgcv ))
shhh(library(dplyr))
shhh(library(ggplot2))
shhh(library(lme4))
shhh(library(tidymv))
shhh(library(gamlss))
shhh(library(gsubfn))
shhh(library(lmerTest))
shhh(library(tidyverse))
shhh(library(boot))
shhh(library(rsample))
shhh(library(plotrix))
shhh(library(ggrepel))
shhh(library(mgcv))

theme_set(theme_bw())
options(digits=4)
options(dplyr.summarise.inform = FALSE)
```


## Combine Modeling Results

```{r}
curr_ref_df = read.csv("../data/provo_refs.tsv", sep="\t") %>% dplyr::select(-X, -Word_Cleaned, -Word) %>%
  rename(TEXT_ID = Text_ID,
         SENT_IDX = Sentence_Number,
         CURRENT_FIX_SENT_IDX = Word_In_Sentence_Number,
         CURRENT_FIX_INTEREST_AREA_INDEX = Word_Number)

next_ref_df = read.csv("../data/provo_refs.tsv", sep="\t") %>% dplyr::select(-X, -Word_Cleaned, -Word) %>%
  rename(TEXT_ID = Text_ID,
         SENT_IDX = Sentence_Number,
         NEXT_FIX_SENT_IDX = Word_In_Sentence_Number,
         NEXT_FIX_INTEREST_AREA_INDEX = Word_Number)
```


```{r}

stats_df = data.frame()
results_path = "../data/results/by_sentence_results"
results_list = list.files(path=results_path, pattern=".csv")

for (f in results_list) {
  df = read.csv(paste0(results_path, "/", f))
  stats_df = rbind(stats_df, df)
}

modeling_df = stats_df %>%
  dplyr::select(-X) %>%
  mutate(target_idx = target_idx + 1, trigger_idx = trigger_idx + 1) %>% # 0-indexing vs. 1-indexing for human data
  rename(TEXT_ID = text_id,
         SENT_IDX = sent_id,
         CURRENT_FIX_SENT_IDX = trigger_idx,
         NEXT_FIX_SENT_IDX = target_idx) %>%
  
  merge( curr_ref_df, by=c("TEXT_ID", "SENT_IDX", "CURRENT_FIX_SENT_IDX")) %>%
  merge( next_ref_df, by=c("TEXT_ID", "SENT_IDX", "NEXT_FIX_SENT_IDX"))


```


## Reference DF

Used to link modeling df to human data df

```{r}
refs_df = read.csv("../data/provo_refs.tsv", sep="\t") %>% dplyr::select(-X) %>%
  rename(CURRENT_FIX_INTEREST_AREA_INDEX = Word_Number,
         TEXT_ID = Text_ID)
  
```

## Clean Provo Data

Takes a little while to load
```{r}
provo_df = read.csv("../data/Provo_Corpus-Additional_Eyetracking_Data-Fixation_Report.csv")
```


```{r}

target_df = provo_df %>%
  dplyr::select(CURRENT_FIX_DURATION, CURRENT_FIX_INDEX, CURRENT_FIX_INTEREST_AREAS, CURRENT_FIX_INTEREST_AREA_INDEX, CURRENT_FIX_INTEREST_AREA_LABEL,
                NEXT_FIX_DURATION, NEXT_FIX_INTEREST_AREAS, NEXT_FIX_INTEREST_AREA_INDEX, NEXT_FIX_INTEREST_AREA_LABEL,
                PREVIOUS_FIX_DURATION, PREVIOUS_FIX_INTEREST_AREAS, PREVIOUS_FIX_INTEREST_AREA_INDEX, PREVIOUS_FIX_INTEREST_AREA_LABEL,
                RECORDING_SESSION_LABEL, TRIAL_INDEX, trial, TRIAL_LABEL)

```


```{r}

# DF with all the saccades
sacc_df = target_df %>% rename(TEXT_ID = trial) %>%
  
  merge(refs_df, by = c("TEXT_ID", "CURRENT_FIX_INTEREST_AREA_INDEX")) %>%
  filter(CURRENT_FIX_INTEREST_AREA_INDEX != Word_Cleaned) %>% #No rows are filtered ... good!
  
  rename(SENT_IDX = Sentence_Number, WORD_IDX_IN_SENT = Word_In_Sentence_Number) %>%
  dplyr::select(-Word, -Word_Cleaned, -TRIAL_LABEL, ) %>%
  rename(SUBJ_ID = RECORDING_SESSION_LABEL)
```

```{r}
regress_df = sacc_df %>%
  mutate(NEXT_FIX_INTEREST_AREA_INDEX = as.integer(NEXT_FIX_INTEREST_AREA_INDEX),
         CURRENT_FIX_INTEREST_AREA_INDEX = as.integer(CURRENT_FIX_INTEREST_AREA_INDEX)) %>%
  filter(NEXT_FIX_INTEREST_AREA_INDEX < CURRENT_FIX_INTEREST_AREA_INDEX) %>%
  dplyr::select(-CURRENT_FIX_INTEREST_AREAS, -NEXT_FIX_INTEREST_AREAS, -PREVIOUS_FIX_INTEREST_AREAS) %>%
  mutate(REGRESS_LEN = CURRENT_FIX_INTEREST_AREA_INDEX - NEXT_FIX_INTEREST_AREA_INDEX) %>%

  # Filter out double regressions for the sake of the initial analysis
  filter(CURRENT_FIX_INTEREST_AREA_INDEX >= PREVIOUS_FIX_INTEREST_AREA_INDEX)

regress_agg_df = regress_df %>%
  group_by(TEXT_ID, CURRENT_FIX_INTEREST_AREA_INDEX, NEXT_FIX_INTEREST_AREA_INDEX, WORD_IDX_IN_SENT, SENT_IDX, REGRESS_LEN) %>%
    summarise(
      n_regressions = n(),
      n_subj = length(unique(SUBJ_ID))
    ) %>%
  ungroup()

```


```{r}

agg_df = merge(modeling_df, regress_agg_df, all=T, by=c("TEXT_ID", "SENT_IDX", "CURRENT_FIX_INTEREST_AREA_INDEX", "NEXT_FIX_INTEREST_AREA_INDEX")) %>%
  dplyr::select(-WORD_IDX_IN_SENT) %>%
  rename(trigger_ia_idx=CURRENT_FIX_INTEREST_AREA_INDEX,
         trigger_sent_idx=CURRENT_FIX_SENT_IDX,
         target_ia_idx=NEXT_FIX_INTEREST_AREA_INDEX,
         target_sent_idx=NEXT_FIX_SENT_IDX,
         text_id = TEXT_ID,
         sent_id = SENT_IDX)
agg_df[is.na(agg_df)] = 0

write.csv(agg_df, "../data/regression_df.csv")

```






